### PR TITLE
Add PNG version of openindiana-default background

### PR DESCRIPTION
**Pull request by Mno-hime**
Some compiz plugins can't load JPEG, but can PNG.

File created via: `mogrify -format png openindiana-default.jpg`

### CODE REVIEW

**Comment by pyhalov** [comment]
Don't forget to add file to https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/components/openindiana/openindiana-backgrounds/os-backgrounds.p5m

**Comment by Mno-hime** [comment]
There `imgjpeg` plugin which lets plugins load JPEG image. We don't need this. JPEG plugin is enable by default in compiz.

**Comment by Mno-hime** [comment]
There `imgjpeg` plugin which lets plugins load JPEG image. We don't need this. JPEG plugin is enable by default in compiz.

**Comment by Mno-hime** [comment]
There `imgjpeg` plugin which lets plugins load JPEG image. We don't need this. JPEG plugin is enable by default in compiz.

**Comment by Mno-hime** [comment]
There `imgjpeg` plugin which lets plugins load JPEG image. We don't need this. JPEG plugin is enable by default in compiz.

**Comment by Mno-hime** [comment]
There `imgjpeg` plugin which lets plugins load JPEG image. We don't need this. JPEG plugin is enable by default in compiz.

**Comment by Mno-hime** [comment]
There `imgjpeg` plugin which lets plugins load JPEG image. We don't need this. JPEG plugin is enable by default in compiz.

**Comment by Mno-hime** [comment]
There `imgjpeg` plugin which lets plugins load JPEG image. We don't need this. JPEG plugin is enable by default in compiz.

**Comment by Mno-hime** [comment]
Test.

**Pull request closed without merging**
